spring:
  profiles:
    active:
    - dev
    
---
spring:
  profiles: dev
  application:
    name: microserverclound-config-dev
    
---

spring:
  profiles: test
  application:
    name: microserverclound-config-test